#!/bin/sh
# Take in a directory and assign to a variable.
# Iterate over the given directory.
# Iterate through all the markdown files in that directory.
# Print the first line of the markdown files.

loop() {
for dir in *;do 
	test -d "$dir" || continue 
		for file in "$dir"/*.md; do
			 test -e "$file" || continue
			 read -r a < "$file"
			 echo "$file: $a"	
		done
done
}

loop | less
